### ISSUE TITLE
U3,PracticaN1,Hilos

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/practica-de-hilos-KarlaV0#2]
[TAP,U3,Practica1.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-KarlaV0/files/6517463/TAP.U3.Practica1.pdf)

**Comment by carlos-chrs** [comment]
20

muy bien echo.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
